### ISSUE TITLE
Citation information?

### ISSUE THREAD

**Issue by samumantha** [Lumi-supercomputer/LUMI-AI-Guide#49]
A citation.cff file or any other way of providing citation information would make referring to this wonderful guide easier and give credit to the authors. 

It can be very minimal (with all contributors mentioned as authors, I just started based on commit history), eg. 

```
cff-version: 1.2.0
message: "If you use this material, please cite it using these metadata."
authors:
  - name: "LUMI User Support Team"
  - family-names: "Decristoforo"
    given-names: "Gregor"
  - family-names: "Sødequist"
    given-names: "Joachim"
  - family-names: "Rigazzi "
    given-names: "Al"
  - family-names: "Szpindler "
    given-names: "Maciej"
  - family-names: "Szpindler "
    given-names: "Maciej"
title: "LUMI AI Guide"
type: "data"
abstract: "The LUMI AI Guide is designed to assist users in migrating their machine learning applications from smaller-scale computing environments to the LUMI supercomputer. "
version: 2025-02-27
date-released: 2025-02-27
license: CC-BY-4.0
repository-code: "https://github.com/Lumi-supercomputer/LUMI-AI-Guide"
```
